name: Publish release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          
      - name: Build and publish with Gradle
        run: ./gradlew assemble
          
      - uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659
        with:
          modrinth-id: dBOB3VZD
          modrinth-token: ${{ secrets.MODRINTH }}
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
