name: Publish release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          
      - name: Build and publish with Gradle
        run: ./gradlew modrinth publish
        env:
          BUILD_RELEASE: ${{ github.event.prelease == false }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH }}
          CHANGELOG: ${{ github.event.release.body }}
          
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: dBOB3VZD
          modrinth-token: ${{ secrets.MODRINTH }}
